
import React from 'react';
import { Download, Gavel, ShieldCheck, ArrowLeft, ArrowRight, Loader2 } from 'lucide-react';
import { useLanguage } from '../LanguageContext';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';


const CriminalCertificate = () => {
    const { t, dir } = useLanguage();
    const navigate = useNavigate();
    const isAr = dir === 'rtl';
    
    // Fetch user data from localStorage
    const storedUser = JSON.parse(localStorage.getItem('user') || '{}');
    const userData = {
        fullName: storedUser.full_name || 'Guest User',
        idNumber: storedUser.national_number || storedUser.residence_number || storedUser.national_id_number || 'N/A'
    };

    const [certData, setCertData] = React.useState(null);
    const [loading, setLoading] = React.useState(false);

    const handleRequest = async () => {
        if (userData.idNumber === 'N/A') {
            alert(isAr ? 'لم يتم العثور على رقم هوية في ملفك الشخصي' : 'No ID number found in your profile');
            return;
        }
        setLoading(true);
        try {
            const res = await fetch(`http://localhost:5000/api/user/criminal-status/${userData.idNumber}`);
            const data = await res.json();
            if (data.success) {
                setCertData(data);
            } else {
                alert(data.message || 'Error');
            }
        } catch (e) {
            console.error(e);
            alert('Connection error');
        }
        setLoading(false);
    };

    const downloadPDF = () => {
        if (!certData) return;
        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(11, 21, 40); 
        doc.text("FEDERAL REPUBLIC OF SOMALIA", 105, 20, { align: 'center' });
        
        doc.setFontSize(16);
        doc.text("CRIMINAL RECORD CERTIFICATE", 105, 30, { align: 'center' });
        
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);
        
        // Person Info
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Full Name: ${certData.person.full_name}`, 20, 50);
        doc.text(`ID Number: ${certData.person.id_number}`, 20, 60);
        doc.text(`Nationality: ${certData.person.nationality}`, 20, 70);
        doc.text(`Status: ${certData.hasRecords ? 'RECORDS FOUND' : 'CLEAN RECORD'}`, 20, 80);
        doc.text(`Date of Issue: ${new Date().toLocaleDateString()}`, 20, 90);
        
        if (certData.hasRecords) {
            const tableData = certData.records.map(r => [
                r.crime_type,
                new Date(r.incident_date).toLocaleDateString(),
                r.status,
                r.court_decision || 'N/A'
            ]);
            
            autoTable(doc, {
                startY: 100,
                head: [['Crime Type', 'Date', 'Status', 'Decision']],
                body: tableData,
                theme: 'grid',
                headStyles: { fillColor: [197, 160, 89] }
            });

        } else {
            doc.setFontSize(14);
            doc.setTextColor(0, 150, 0);
            doc.text("THIS INDIVIDUAL HAS NO CRIMINAL RECORDS IN THE NATIONAL DATABASE.", 105, 120, { align: 'center' });
        }
        
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Official document generated by Somalia E-Government Portal", 105, 280, { align: 'center' });
        
        doc.save(`Criminal_Certificate_${certData.person.id_number}.pdf`);
    };

    const BackIcon = isAr ? ArrowRight : ArrowLeft;

    return (
        <div className="bg-[#f8fafc] dark:bg-primary-950 min-h-screen pb-32 pt-24">
            <div className="container mx-auto px-4 max-w-4xl">
                <button 
                    onClick={() => navigate('/services')}
                    className="flex items-center gap-2 text-gray-500 hover:text-primary-600 font-bold mb-8 transition-colors"
                >
                    <BackIcon size={20} /> {t.allServices}
                </button>

                <div className="bg-white dark:bg-slate-900 p-12 rounded-[3rem] shadow-premium border border-gray-100 dark:border-white/10 text-center space-y-8 overflow-hidden relative">
                    <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-blue-600 via-gold-500 to-blue-600"></div>
                    
                    <div className="w-24 h-24 bg-primary-50 dark:bg-white/5 text-primary-900 dark:text-gold-500 rounded-3xl flex items-center justify-center mx-auto shadow-sm">
                        <Gavel size={48} />
                    </div>

                    <div className="space-y-4">
                        <h1 className="text-4xl font-black text-gray-900 dark:text-white tracking-tight">
                            {isAr ? 'خدمة استخراج شهادة السجل الجنائي' : 'Criminal Record Certificate Service'}
                        </h1>
                        <p className="text-gray-500 dark:text-gray-400 font-bold max-w-lg mx-auto">
                            {isAr ? 'احصل على شهادة رسمية فورية ومجانية توضح حالتك الجنائية بناءً على السجلات الوطنية الموحدة.' : 'Get an instant and free official certificate showing your criminal status based on unified national records.'}
                        </p>
                    </div>

                    <div className="grid grid-cols-2 md:grid-cols-3 gap-4 max-w-2xl mx-auto py-6">
                        <div className="p-4 bg-gray-50 dark:bg-white/5 rounded-2xl border border-gray-100 dark:border-white/5">
                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">{t.feesLabel}</p>
                            <p className="font-black text-emerald-600">{isAr ? 'مجاني' : 'FREE'}</p>
                        </div>
                        <div className="p-4 bg-gray-50 dark:bg-white/5 rounded-2xl border border-gray-100 dark:border-white/5">
                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">{t.durationLabel}</p>
                            <p className="font-black text-primary-900 dark:text-white">{isAr ? 'فوري' : 'INSTANT'}</p>
                        </div>
                        <div className="p-4 bg-gray-50 dark:bg-white/5 rounded-2xl border border-gray-100 dark:border-white/5 col-span-2 md:col-span-1">
                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Status</p>
                            <p className="font-black text-primary-900 dark:text-white">Official</p>
                        </div>
                    </div>

                    {!certData ? (
                        <button 
                            onClick={handleRequest}
                            disabled={loading}
                            className="px-12 py-5 bg-primary-950 dark:bg-gold-500 text-white dark:text-primary-950 font-black text-xl rounded-2xl hover:scale-105 transition-all shadow-glow-blue dark:shadow-glow-gold flex items-center justify-center gap-3 mx-auto disabled:opacity-50"
                        >
                            {loading ? <Loader2 className="animate-spin" /> : <ShieldCheck />}
                            {isAr ? 'إصدار الشهادة الآن' : 'Issue Certificate Now'}
                        </button>
                    ) : (
                        <div className="animate-fade-in space-y-8 pt-8 border-t border-gray-100 dark:border-white/5">
                            <div className={`p-8 rounded-[2rem] flex flex-col items-center gap-6 ${certData.hasRecords ? 'bg-red-50 dark:bg-red-900/10 border border-red-100' : 'bg-emerald-50 dark:bg-emerald-900/10 border border-emerald-100'}`}>
                                <div className={`w-16 h-16 rounded-full flex items-center justify-center text-white ${certData.hasRecords ? 'bg-red-500' : 'bg-emerald-500'}`}>
                                    {certData.hasRecords ? <Gavel size={32} /> : <ShieldCheck size={32} />}
                                </div>
                                <div>
                                    <h3 className={`text-2xl font-black ${certData.hasRecords ? 'text-red-900 dark:text-red-400' : 'text-emerald-900 dark:text-emerald-400'}`}>
                                        {certData.hasRecords ? (isAr ? 'يوجد سجل جنائي مسجل' : 'Criminal Records Found') : (isAr ? 'السجل نظيف - لا توجد سوابق' : 'Clear Record - No Criminal History')}
                                    </h3>
                                    <p className="text-gray-500 font-bold mt-2">{certData.person.full_name}</p>
                                </div>

                                <button 
                                    onClick={downloadPDF}
                                    className="px-10 py-4 bg-emerald-600 text-white font-black rounded-2xl hover:scale-105 transition-all shadow-lg flex items-center gap-3"
                                >
                                    <Download /> {isAr ? 'تحميل الشهادة (PDF)' : 'Download Certificate (PDF)'}
                                </button>
                            </div>

                            <button onClick={() => setCertData(null)} className="text-gray-400 font-bold underline text-sm">
                                {isAr ? 'طلب شهادة جديدة' : 'Request New Certificate'}
                            </button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default CriminalCertificate;
