
import React from 'react';
import {
    User, Mail, Phone, CreditCard, ShieldCheck,
    Award, Globe, Plus, Fingerprint, Calendar, Shield, QrCode, FileText, Download, Gavel
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';


import { useLanguage } from '../LanguageContext';
import { useNavigate } from 'react-router-dom';

const Profile = () => {
    const { t, dir } = useLanguage();
    const navigate = useNavigate();
    const [myRequests, setMyRequests] = React.useState([]);

    // Fetch user data from localStorage
    const storedUser = JSON.parse(localStorage.getItem('user') || '{}');

    const [certData, setCertData] = React.useState(null);
    const [certLoading, setCertLoading] = React.useState(false);

    React.useEffect(() => {
        const fetchRequests = async () => {
            if (!storedUser.account_type) return;
            const accId = storedUser.citizen_id || storedUser.resident_id || storedUser.user_id;
            try {
                const res = await fetch(`http://localhost:5000/api/user/requests?type=${storedUser.account_type}&id=${accId}`);
                const data = await res.json();
                if (data.success) {
                    setMyRequests(data.requests);
                }
            } catch (e) { console.error(e); }
        };
        fetchRequests();
    }, [storedUser.account_type, storedUser.citizen_id, storedUser.resident_id, storedUser.user_id]);

    const handleRequestCertificate = async () => {
        setCertLoading(true);
        try {
            const res = await fetch(`http://localhost:5000/api/user/criminal-status/${userData.idNumber}`);
            const data = await res.json();
            if (data.success) {
                setCertData(data);
            } else {
                alert(data.message || 'Error fetching status');
            }
        } catch (e) {
            console.error(e);
            alert('Connection error');
        }
        setCertLoading(false);
    };

    const downloadPDF = () => {
        if (!certData) return;
        const doc = new jsPDF();
        const isAr = dir === 'rtl';
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(11, 21, 40); // Primary color
        doc.text("FEDERAL REPUBLIC OF SOMALIA", 105, 20, { align: 'center' });
        
        doc.setFontSize(16);
        doc.text("CRIMINAL RECORD CERTIFICATE", 105, 30, { align: 'center' });
        
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);
        
        // Person Info
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Full Name: ${certData.person.full_name}`, 20, 50);
        doc.text(`ID Number: ${certData.person.id_number}`, 20, 60);
        doc.text(`Nationality: ${certData.person.nationality}`, 20, 70);
        doc.text(`Status: ${certData.hasRecords ? 'RECORDS FOUND' : 'CLEAN RECORD'}`, 20, 80);
        doc.text(`Date of Issue: ${new Date().toLocaleDateString()}`, 20, 90);
        
        if (certData.hasRecords) {
            const tableData = certData.records.map(r => [
                r.crime_type,
                new Date(r.incident_date).toLocaleDateString(),
                r.status,
                r.court_decision || 'N/A'
            ]);
            
            autoTable(doc, {
                startY: 100,
                head: [['Crime Type', 'Date', 'Status', 'Decision']],
                body: tableData,
                theme: 'grid',
                headStyles: { fillColor: [197, 160, 89] } // Gold color
            });

        } else {
            doc.setFontSize(14);
            doc.setTextColor(0, 150, 0);
            doc.text("THIS INDIVIDUAL HAS NO CRIMINAL RECORDS IN THE NATIONAL DATABASE.", 105, 120, { align: 'center' });
        }
        
        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("This is an official document generated by the Somalia National Identity Portal.", 105, 280, { align: 'center' });
        
        doc.save(`Criminal_Certificate_${certData.person.id_number}.pdf`);
    };


    const userData = {
        firstName: storedUser.full_name?.split(' ')[0] || '',
        middleName: storedUser.full_name?.split(' ').slice(1, -1).join(' ') || '',
        lastName: storedUser.full_name?.split(' ').slice(-1)[0] || '',
        fullName: storedUser.full_name || 'Guest User',
        email: storedUser.email || storedUser.username || '',
        phone: storedUser.phone || storedUser.phone_number || '',
        idNumber: storedUser.national_number || storedUser.residence_number || storedUser.national_id_number || 'N/A', // Support both Citizen ID and Resident Number
        accountType: storedUser.account_type || 'citizen',
        nid: storedUser.id || 'N/A',
        dob: storedUser.dob || 'N/A',
        pob: storedUser.place_of_birth || 'N/A',
        gender: storedUser.gender || 'N/A',
        nationality: storedUser.nationality || 'Somali',
        passportNumber: storedUser.passport_number || 'N/A',
        expiryId: storedUser.id_expiry || 'N/A',
        expiryPassport: storedUser.passport_expiry || 'N/A'
    };

    const SectionHeader = ({ icon: Icon, title }) => (
        <div className="flex items-center gap-4 mb-8 border-b border-gray-100 dark:border-white/5 pb-4">
            <div className="w-10 h-10 bg-primary-900 dark:bg-gold-500 text-white dark:text-primary-950 rounded-xl flex items-center justify-center">
                <Icon size={20} />
            </div>
            <h3 className="text-2xl font-black text-gray-900 dark:text-white tracking-tight">{title}</h3>
        </div>
    );

    return (
        <div className="bg-[#f8fafc] dark:bg-primary-950 min-h-screen pb-32 transition-colors duration-500">

            <div className="bg-primary-950 pt-20 pb-48 relative overflow-hidden">
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-primary-800/40 via-transparent to-transparent"></div>
                <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(#ffffff 1px, transparent 1px)', backgroundSize: '40px 40px' }}></div>

                <div className="container mx-auto px-4 relative z-10">
                    <div className="flex flex-col md:flex-row items-center gap-8 animate-fade-in-up">
                        <div className="relative group">
                            <div className="w-32 h-32 rounded-[2.5rem] bg-white/10 backdrop-blur-xl border-4 border-white/20 p-1 overflow-hidden shadow-2xl relative">
                                <img
                                    src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=200"
                                    alt="User Avatar"
                                    className="w-full h-full object-cover rounded-[2rem]"
                                />
                            </div>
                            <div className="absolute -bottom-1 -right-1 w-10 h-10 bg-green-500 rounded-2xl border-4 border-primary-950 flex items-center justify-center text-white">
                                <ShieldCheck size={18} />
                            </div>
                        </div>

                        <div className="text-center md:text-start space-y-3">
                            <h1 className="text-4xl font-black text-white tracking-tight">{userData.fullName}</h1>
                            <div className="flex flex-wrap justify-center md:justify-start gap-3">
                                <span className="flex items-center gap-2 text-primary-200 text-xs font-bold bg-white/5 px-4 py-2 rounded-full border border-white/10 uppercase tracking-widest">
                                    <CreditCard size={14} className="text-gold-500" />
                                    {userData.idNumber}
                                </span>
                                <span className="flex items-center gap-2 text-primary-200 text-xs font-bold bg-white/5 px-4 py-2 rounded-full border border-white/10 uppercase tracking-widest">
                                    <Shield size={14} className="text-gold-500" />
                                    Verified Identity
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="container mx-auto px-4 -mt-24 relative z-20 space-y-12">

                <div className="bg-white dark:bg-slate-900/50 p-10 rounded-[3rem] shadow-premium border border-gray-100 dark:border-white/10">
                    <SectionHeader icon={User} title={t.personalInfo} />
                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-y-10 gap-x-8">
                        {[
                            { label: t.fullName, val: userData.fullName, icon: User },
                            { label: t.nid, val: userData.nid, icon: Fingerprint },
                            { label: t.emailOrId, val: userData.email, icon: Mail },
                            { label: t.phoneNumber, val: userData.phone, icon: Phone },
                            { label: t.dob, val: userData.dob, icon: Calendar },
                            { label: t.nationality, val: userData.nationality, icon: Globe },
                        ].map((item, i) => (
                            <div key={i} className="space-y-1 group">
                                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest flex items-center gap-2">
                                    <item.icon size={12} className="text-primary-600 dark:text-gold-500" />
                                    {item.label}
                                </p>
                                <p className="text-gray-900 dark:text-white font-black text-lg group-hover:text-primary-600 dark:group-hover:text-gold-400 transition-colors">{item.val}</p>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="grid lg:grid-cols-2 gap-12">
                    <div className="space-y-6">
                        <div className="flex justify-between items-center gap-2">
                            <h4 className="text-xs font-black text-gray-400 uppercase tracking-[0.2em]">{t.idServices || 'ID SERVICES'}</h4>
                            <div className="flex gap-2">
                                <button onClick={() => navigate('/service/id-renew')} className="px-4 py-2 bg-primary-50 dark:bg-white/5 hover:bg-primary-600 hover:text-white dark:hover:bg-primary-600 dark:hover:text-white text-primary-900 font-black rounded-xl text-[10px] transition-all flex items-center gap-2">
                                    <Plus size={14} /> {t.services?.idRenew || 'Renew'}
                                </button>
                                <button onClick={() => navigate('/service/id-replace')} className="px-4 py-2 bg-primary-50 dark:bg-white/5 hover:bg-primary-600 hover:text-white dark:hover:bg-primary-600 dark:hover:text-white text-primary-900 font-black rounded-xl text-[10px] transition-all flex items-center gap-2">
                                    <Plus size={14} /> {dir === 'rtl' ? 'بدل فاقد' : 'Replace'}
                                </button>
                            </div>
                        </div>

                        <div className="relative w-full max-w-[500px] h-[300px] rounded-[2rem] overflow-hidden shadow-2xl group mx-auto md:mx-0">
                            <div className="absolute inset-0 bg-gradient-to-br from-white via-gray-50 to-blue-50 dark:from-primary-900 dark:to-primary-950 border border-white/20"></div>
                            <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-blue-600 via-white to-blue-600"></div>

                            <div className="relative h-full p-8 flex flex-col justify-between">
                                <div className="flex justify-between items-start">
                                    <div className="flex items-center gap-3">
                                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Coat_of_arms_of_Somalia.svg/200px-Coat_of_arms_of_Somalia.svg.png" className="w-10 h-10" alt="Logo" />
                                        <div>
                                            <h5 className="text-[10px] font-black text-blue-900 dark:text-white uppercase leading-none">Federal Republic of Somalia</h5>
                                            <p className="text-[8px] font-bold text-blue-700/60 dark:text-gold-500/60 uppercase">National Identity Card</p>
                                        </div>
                                    </div>
                                    <div className="bg-white/50 backdrop-blur-sm p-2 rounded-lg border border-white/40">
                                        <QrCode size={40} className="text-blue-900" />
                                    </div>
                                </div>

                                <div className="flex gap-6 mt-2 items-center">
                                    <div className="flex-grow space-y-4 order-2 md:order-1 ltr:text-left rtl:text-right">
                                        <div className="space-y-0.5">
                                            <label className="text-[7px] font-black text-blue-400 uppercase">Full Name</label>
                                            <p className="text-sm font-black text-blue-900 dark:text-white">{userData.fullName}</p>
                                        </div>
                                        <div className="grid grid-cols-2 gap-4">
                                            <div className="space-y-0.5">
                                                <label className="text-[7px] font-black text-blue-400 uppercase">National ID</label>
                                                <p className="text-xs font-black text-blue-900 dark:text-white">{userData.idNumber}</p>
                                            </div>
                                            <div className="space-y-0.5">
                                                <label className="text-[7px] font-black text-blue-400 uppercase">Expiry Date</label>
                                                <p className="text-xs font-black text-red-600">{userData.expiryId}</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="w-28 h-32 bg-gray-100 rounded-xl overflow-hidden border-2 border-white shadow-md order-1 md:order-2">
                                        <img src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=200" className="w-full h-full object-cover" alt="ID" />
                                    </div>
                                </div>

                                <div className="mt-4 flex justify-between items-end">
                                    <span className="text-[14px] font-mono font-black text-blue-900/30 tracking-[0.3em]">SO992812739812</span>
                                    <Award className="text-gold-500" size={24} />
                                </div>
                            </div>
                        </div>
                    </div>

                    {userData.accountType !== 'resident' && (
                        <div className="space-y-6">
                            <div className="flex justify-between items-center gap-2">
                                <h4 className="text-xs font-black text-gray-400 uppercase tracking-[0.2em]">{t.passportServices || 'PASSPORT SERVICES'}</h4>
                                <div className="flex gap-2">
                                    <button onClick={() => navigate('/service/passport-renew')} className="px-4 py-2 bg-primary-50 dark:bg-white/5 hover:bg-primary-600 hover:text-white dark:hover:bg-primary-600 dark:hover:text-white text-primary-900 font-black rounded-xl text-[10px] transition-all flex items-center gap-2">
                                        <Plus size={14} /> {t.services?.pptRenew || 'Renew'}
                                    </button>
                                    <button onClick={() => navigate('/service/passport-replace')} className="px-4 py-2 bg-primary-50 dark:bg-white/5 hover:bg-primary-600 hover:text-white dark:hover:bg-primary-600 dark:hover:text-white text-primary-900 font-black rounded-xl text-[10px] transition-all flex items-center gap-2">
                                        <Plus size={14} /> {dir === 'rtl' ? 'بدل فاقد' : 'Replace'}
                                    </button>
                                </div>
                            </div>

                            <div className="relative w-full max-w-[500px] h-[300px] rounded-[2rem] overflow-hidden shadow-2xl group bg-[#fdfaf2] border border-[#e8dfc9] mx-auto md:mx-0">
                                <div className="relative h-full p-8 flex flex-col">
                                    <div className="flex justify-between items-start mb-6">
                                        <div>
                                            <h5 className="text-[10px] font-black text-amber-900 uppercase">Somali Passport / Baasaboor</h5>
                                            <p className="text-[7px] text-amber-800 font-bold uppercase tracking-widest">Federal Republic of Somalia</p>
                                        </div>
                                        <span className="text-amber-900 font-black text-lg font-mono">P &lt; SOM &lt;&lt;</span>
                                    </div>

                                    <div className="flex gap-8 flex-1">
                                        <div className="w-28 h-36 bg-gray-100 rounded-lg overflow-hidden border border-amber-200 grayscale-[0.3] shadow-inner">
                                            <img src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=200" className="w-full h-full object-cover" alt="Passport" />
                                        </div>

                                        <div className="flex-1 grid grid-cols-2 gap-y-4 gap-x-2">
                                            <div className="col-span-2">
                                                <label className="text-[6px] text-amber-800 font-black uppercase block">Surname / Magaca</label>
                                                <p className="text-xs font-black text-amber-950">{userData.lastName}</p>
                                            </div>
                                            <div className="col-span-2">
                                                <label className="text-[6px] text-amber-800 font-black uppercase block">Given Names</label>
                                                <p className="text-xs font-black text-amber-950">{userData.firstName} {userData.middleName}</p>
                                            </div>
                                            <div>
                                                <label className="text-[6px] text-amber-800 font-black uppercase block">Date of Expiry</label>
                                                <p className="text-xs font-black text-red-700">{userData.expiryPassport}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* My Requests Section */}
                <div className="bg-white dark:bg-slate-900/50 p-10 rounded-[3rem] shadow-premium border border-gray-100 dark:border-white/10 mt-12">
                    <SectionHeader icon={FileText} title={dir === 'rtl' ? 'طلباتي' : 'My Requests'} />
                    {myRequests.length === 0 ? (
                        <p className="text-gray-500 font-bold">{dir === 'rtl' ? 'لا يوجد طلبات حالياً.' : 'No requests currently.'}</p>
                    ) : (
                        <div className="space-y-4">
                            {myRequests.map((req, i) => (
                                <div key={i} className="flex justify-between items-center p-5 bg-gray-50 dark:bg-black/20 rounded-2xl border border-gray-100 dark:border-white/5">
                                    <div>
                                        <h5 className="font-black text-gray-900 dark:text-white uppercase">{req.service_type.replace('_', ' ')}</h5>
                                        <p className="text-xs font-bold text-gray-500">{new Date(req.request_date).toLocaleDateString()}</p>
                                    </div>
                                    <span className={`px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest ${
                                        req.status === 'approved' ? 'bg-green-100 text-green-700 dark:bg-green-900/30' :
                                        req.status === 'rejected' ? 'bg-red-100 text-red-700 dark:bg-red-900/30' :
                                        'bg-blue-100 text-blue-700 dark:bg-blue-900/30'
                                    }`}>
                                        {req.status.replace('_', ' ')}
                                    </span>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Criminal Record Certificate Section */}
                <div className="bg-white dark:bg-slate-900/50 p-10 rounded-[3rem] shadow-premium border border-gray-100 dark:border-white/10 mt-12">
                    <SectionHeader icon={Gavel} title={dir === 'rtl' ? 'شهادة خلو سوابق' : 'Criminal Record Certificate'} />
                    
                    <div className="flex flex-col md:flex-row items-center justify-between gap-8 bg-primary-50/50 dark:bg-white/5 p-8 rounded-3xl border border-primary-100 dark:border-white/10">
                        <div className="space-y-2">
                            <h4 className="text-xl font-black text-primary-950 dark:text-white">{dir === 'rtl' ? 'طلب شهادة الحالة الجنائية' : 'Request Criminal Status Certificate'}</h4>
                            <p className="text-sm text-gray-500 dark:text-gray-400 font-bold">{dir === 'rtl' ? 'يمكنك الحصول على شهادة رسمية بحالتك الجنائية مجاناً.' : 'Get an official certificate of your criminal status for free.'}</p>
                        </div>
                        
                        {!certData ? (
                            <button 
                                onClick={handleRequestCertificate}
                                disabled={certLoading}
                                className="px-8 py-4 bg-primary-900 dark:bg-gold-500 text-white dark:text-primary-950 font-black rounded-2xl hover:scale-105 transition-all shadow-xl disabled:opacity-50"
                            >
                                {certLoading ? '...' : (dir === 'rtl' ? 'طلب الآن' : 'Request Now')}
                            </button>
                        ) : (
                            <div className="flex flex-col items-center gap-4">
                                <div className={`px-6 py-3 rounded-2xl font-black text-sm uppercase tracking-widest ${certData.hasRecords ? 'bg-red-100 text-red-600' : 'bg-green-100 text-green-600'}`}>
                                    {certData.hasRecords ? (dir === 'rtl' ? 'يوجد سجل جنائي' : 'Records Found') : (dir === 'rtl' ? 'لا يوجد سوابق' : 'No Records Found')}
                                </div>
                                <button 
                                    onClick={downloadPDF}
                                    className="flex items-center gap-2 px-6 py-3 bg-emerald-600 text-white font-black rounded-2xl hover:scale-105 transition-all shadow-lg"
                                >
                                    <Download size={18} /> {dir === 'rtl' ? 'تحميل التقرير PDF' : 'Download PDF Report'}
                                </button>
                                <button onClick={() => setCertData(null)} className="text-xs text-gray-400 underline">{dir === 'rtl' ? 'طلب جديد' : 'New Request'}</button>
                            </div>
                        )}
                    </div>

                    {certData && certData.hasRecords && (
                        <div className="mt-8 overflow-x-auto rounded-3xl border border-gray-100 dark:border-white/10">
                            <table className="w-full text-left ltr:text-left rtl:text-right">
                                <thead className="bg-gray-50 dark:bg-white/5">
                                    <tr>
                                        <th className="px-6 py-4 text-xs font-black text-gray-400 uppercase tracking-widest">{dir === 'rtl' ? 'الجريمة' : 'Crime'}</th>
                                        <th className="px-6 py-4 text-xs font-black text-gray-400 uppercase tracking-widest">{dir === 'rtl' ? 'التاريخ' : 'Date'}</th>
                                        <th className="px-6 py-4 text-xs font-black text-gray-400 uppercase tracking-widest">{dir === 'rtl' ? 'الحالة' : 'Status'}</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100 dark:divide-white/5">
                                    {certData.records.map((r, i) => (
                                        <tr key={i} className="hover:bg-gray-50/50 dark:hover:bg-white/5 transition-colors">
                                            <td className="px-6 py-4 font-bold text-gray-900 dark:text-white">{r.crime_type}</td>
                                            <td className="px-6 py-4 text-sm text-gray-500">{new Date(r.incident_date).toLocaleDateString()}</td>
                                            <td className="px-6 py-4">
                                                <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase ${r.status === 'open' ? 'bg-amber-100 text-amber-700' : 'bg-green-100 text-green-700'}`}>
                                                    {r.status}
                                                </span>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>


            </div>
        </div>
    );
};

export default Profile;
